### ISSUE TITLE
Erorr client-php.git

### ISSUE THREAD

**Issue by gksbertas** [smsgatewayme/client-php#1]
[RuntimeException]
  Failed to clone https://github.com/smsgatewayme/client-php.git, git was not
   found, check that it is installed and in your PATH env.

  sh: 1: git: not found

**Comment by sepehrs** [comment]
Hi,
In order to import libraries using composer you will need to have git installed.

For full requirements of composer please visit:
https://getcomposer.org/doc/00-intro.md#system-requirements
